In [1]:
import pandas as pd

In [2]:
all_xgb_pred=pd.read_csv('/home/jiayi/5moU/data/DL_fromTombo/all_xgb_pred.csv')
all_xgb_pred

,indx,kmer,mean_1,mean_2,mean_3,mean_4,mean_5,std_1,std_2,std_3,...,mdintense_4,mdintense_5,L-1,L-2,L-3,L-4,L-5,label,prediction,prob
0,20,CATCT,-0.261382,-0.290529,-0.375176,-0.548695,-0.420694,0.034490,0.048193,0.075762,...,-0.548282,-0.413797,6,19,12,50,6,1,1,0.870557
1,22,TCTTC,-0.375176,-0.548695,-0.420694,-0.102165,0.324141,0.075762,0.072908,0.065934,...,-0.103449,0.339314,12,50,6,29,12,1,1,0.955709
2,23,CTTCG,-0.548695,-0.420694,-0.102165,0.324141,0.612248,0.072908,0.065934,0.077537,...,0.339314,0.643455,50,6,29,12,24,1,1,0.973307
3,35,CGTGG,-0.134270,0.017096,0.317245,0.286391,0.191036,0.240493,0.116132,0.178935,...,0.264830,0.208968,29,38,6,19,6,1,0,0.161993
4,44,CCTGC,-1.068734,-0.164691,0.164829,0.237456,-0.655237,0.200275,0.057011,0.052036,...,0.240002,-0.657938,131,35,18,39,72,1,1,0.999986
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1822819,350,GCTGG,0.160716,0.201952,0.291149,0.341133,0.261907,0.102909,0.062878,0.118291,...,0.343161,0.269796,22,6,980,14,6,0,0,0.044694
1822820,365,GATCC,0.713934,0.005522,-0.667390,-0.689873,-0.575091,0.217518,0.459278,0.056848,...,-0.655557,-0.570358,6,6,6,16,6,0,0,0.015414
1822821,374,GATCC,0.404221,0.204545,-0.725696,-0.713145,0.062983,0.418295,0.532178,0.098837,...,-0.707623,0.059166,10,7,2203,6,625,0,0,0.000200
1822822,377,CCTGA,-0.713145,0.062983,0.264506,0.270585,0.073087,0.044437,0.174422,0.070813,...,0.250863,0.134898,6,625,34,6,17,0,0,0.058123
1822823,380,GATCA,0.270585,0.073087,-0.577806,-0.538803,0.255019,0.056049,0.242040,0.213394,...,-0.579825,0.257963,6,17,211,6,82,0,0,0.005027

In [9]:
sites=all_xgb_pred['indx']
prob=all_xgb_pred['prob']

In [3]:
Visual=all_xgb_pred[['indx','kmer','label']]
Visual

         indx   kmer  label
0          20  CATCT      1
1          22  TCTTC      1
2          23  CTTCG      1
3          35  CGTGG      1
4          44  CCTGC      1
...       ...    ...    ...
1822819   350  GCTGG      0
1822820   365  GATCC      0
1822821   374  GATCC      0
1822822   377  CCTGA      0
1822823   380  GATCA      0

[1822824 rows x 3 columns]

In [4]:
Visual['XGB_prob']=all_xgb_pred['prob']
Visual

/tmp/ipykernel_677391/1845215218.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Visual['XGB_prob']=all_xgb_pred['prob']

         indx   kmer  label  XGB_prob
0          20  CATCT      1  0.870557
1          22  TCTTC      1  0.955709
2          23  CTTCG      1  0.973307
3          35  CGTGG      1  0.161993
4          44  CCTGC      1  0.999986
...       ...    ...    ...       ...
1822819   350  GCTGG      0  0.044694
1822820   365  GATCC      0  0.015414
1822821   374  GATCC      0  0.000200
1822822   377  CCTGA      0  0.058123
1822823   380  GATCA      0  0.005027

[1822824 rows x 4 columns]

In [5]:
all_RF_pred=pd.read_csv('/home/jiayi/5moU/data/DL_fromTombo/all_RF_pred.csv')
all_RF_pred

,indx,kmer,mean_1,mean_2,mean_3,mean_4,mean_5,std_1,std_2,std_3,...,mdintense_4,mdintense_5,L-1,L-2,L-3,L-4,L-5,label,prediction,prob
0,20,CATCT,-0.261382,-0.290529,-0.375176,-0.548695,-0.420694,0.034490,0.048193,0.075762,...,-0.548282,-0.413797,6,19,12,50,6,1,1,0.83
1,22,TCTTC,-0.375176,-0.548695,-0.420694,-0.102165,0.324141,0.075762,0.072908,0.065934,...,-0.103449,0.339314,12,50,6,29,12,1,1,0.97
2,23,CTTCG,-0.548695,-0.420694,-0.102165,0.324141,0.612248,0.072908,0.065934,0.077537,...,0.339314,0.643455,50,6,29,12,24,1,1,0.93
3,35,CGTGG,-0.134270,0.017096,0.317245,0.286391,0.191036,0.240493,0.116132,0.178935,...,0.264830,0.208968,29,38,6,19,6,1,1,0.72
4,44,CCTGC,-1.068734,-0.164691,0.164829,0.237456,-0.655237,0.200275,0.057011,0.052036,...,0.240002,-0.657938,131,35,18,39,72,1,1,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1822819,350,GCTGG,0.160716,0.201952,0.291149,0.341133,0.261907,0.102909,0.062878,0.118291,...,0.343161,0.269796,22,6,980,14,6,0,0,0.05
1822820,365,GATCC,0.713934,0.005522,-0.667390,-0.689873,-0.575091,0.217518,0.459278,0.056848,...,-0.655557,-0.570358,6,6,6,16,6,0,0,0.10
1822821,374,GATCC,0.404221,0.204545,-0.725696,-0.713145,0.062983,0.418295,0.532178,0.098837,...,-0.707623,0.059166,10,7,2203,6,625,0,0,0.05
1822822,377,CCTGA,-0.713145,0.062983,0.264506,0.270585,0.073087,0.044437,0.174422,0.070813,...,0.250863,0.134898,6,625,34,6,17,0,0,0.10
1822823,380,GATCA,0.270585,0.073087,-0.577806,-0.538803,0.255019,0.056049,0.242040,0.213394,...,-0.579825,0.257963,6,17,211,6,82,0,0,0.03

In [9]:
Visual['RF_prob']=all_RF_pred['prob']
Visual

/tmp/ipykernel_677391/4117530125.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Visual['RF_prob']=all_RF_pred['prob']

         indx   kmer  label  XGB_prob  RF_prob
0          20  CATCT      1  0.870557     0.83
1          22  TCTTC      1  0.955709     0.97
2          23  CTTCG      1  0.973307     0.93
3          35  CGTGG      1  0.161993     0.72
4          44  CCTGC      1  0.999986     1.00
...       ...    ...    ...       ...      ...
1822819   350  GCTGG      0  0.044694     0.05
1822820   365  GATCC      0  0.015414     0.10
1822821   374  GATCC      0  0.000200     0.05
1822822   377  CCTGA      0  0.058123     0.10
1822823   380  GATCA      0  0.005027     0.03

[1822824 rows x 5 columns]

In [10]:
all_SVM_pred=pd.read_csv('/home/jiayi/5moU/data/DL_fromTombo/all_SVM_pred.csv')
all_SVM_pred

,indx,kmer,mean_1,mean_2,mean_3,mean_4,mean_5,std_1,std_2,std_3,...,mdintense_4,mdintense_5,L-1,L-2,L-3,L-4,L-5,label,prediction,prob
0,20,CATCT,-0.261382,-0.290529,-0.375176,-0.548695,-0.420694,0.034490,0.048193,0.075762,...,-0.548282,-0.413797,6,19,12,50,6,1,1,0.742585
1,22,TCTTC,-0.375176,-0.548695,-0.420694,-0.102165,0.324141,0.075762,0.072908,0.065934,...,-0.103449,0.339314,12,50,6,29,12,1,1,0.976235
2,23,CTTCG,-0.548695,-0.420694,-0.102165,0.324141,0.612248,0.072908,0.065934,0.077537,...,0.339314,0.643455,50,6,29,12,24,1,1,0.980302
3,35,CGTGG,-0.134270,0.017096,0.317245,0.286391,0.191036,0.240493,0.116132,0.178935,...,0.264830,0.208968,29,38,6,19,6,1,0,0.306606
4,44,CCTGC,-1.068734,-0.164691,0.164829,0.237456,-0.655237,0.200275,0.057011,0.052036,...,0.240002,-0.657938,131,35,18,39,72,1,1,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1822819,350,GCTGG,0.160716,0.201952,0.291149,0.341133,0.261907,0.102909,0.062878,0.118291,...,0.343161,0.269796,22,6,980,14,6,0,0,0.005096
1822820,365,GATCC,0.713934,0.005522,-0.667390,-0.689873,-0.575091,0.217518,0.459278,0.056848,...,-0.655557,-0.570358,6,6,6,16,6,0,0,0.043084
1822821,374,GATCC,0.404221,0.204545,-0.725696,-0.713145,0.062983,0.418295,0.532178,0.098837,...,-0.707623,0.059166,10,7,2203,6,625,0,0,0.099116
1822822,377,CCTGA,-0.713145,0.062983,0.264506,0.270585,0.073087,0.044437,0.174422,0.070813,...,0.250863,0.134898,6,625,34,6,17,0,0,0.066001
1822823,380,GATCA,0.270585,0.073087,-0.577806,-0.538803,0.255019,0.056049,0.242040,0.213394,...,-0.579825,0.257963,6,17,211,6,82,0,0,0.002302

In [11]:
Visual['SVM_prob']=all_SVM_pred['prob']
Visual

/tmp/ipykernel_677391/2304149042.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Visual['SVM_prob']=all_SVM_pred['prob']

         indx   kmer  label  XGB_prob  RF_prob  SVM_prob
0          20  CATCT      1  0.870557     0.83  0.742585
1          22  TCTTC      1  0.955709     0.97  0.976235
2          23  CTTCG      1  0.973307     0.93  0.980302
3          35  CGTGG      1  0.161993     0.72  0.306606
4          44  CCTGC      1  0.999986     1.00  1.000000
...       ...    ...    ...       ...      ...       ...
1822819   350  GCTGG      0  0.044694     0.05  0.005096
1822820   365  GATCC      0  0.015414     0.10  0.043084
1822821   374  GATCC      0  0.000200     0.05  0.099116
1822822   377  CCTGA      0  0.058123     0.10  0.066001
1822823   380  GATCA      0  0.005027     0.03  0.002302

[1822824 rows x 6 columns]

1822824

In [15]:
Mod=Visual[Visual['label']==1]
Mod
Mod.to_csv('/home/jiayi/5moU/data/DL_fromTombo/Mod_prob.csv',index=False)

In [16]:
Normal=Visual[Visual['label']==0]
Normal.to_csv('/home/jiayi/5moU/data/DL_fromTombo/Normal_prob.csv',index=False)

In [23]:
Mod['indx'].value_counts()

41      458
206     448
38      425
260     418
95      416
       ...
1560      1
1496      1
1462      1
1460      1
1580      1
Name: indx, Length: 1602, dtype: int64

In [17]:
demo_mod_20=Mod[Mod['indx']==20]
demo_mod_20

        indx   kmer  label  XGB_prob  RF_prob  SVM_prob
0         20  CATCT      1  0.870557     0.83  0.742585
29        20  CCTGC      1  0.999907     1.00  1.000000
621       20  GATCA      1  0.667301     0.70  0.067551
702       20  AGTAC      1  0.997501     1.00  0.995541
2029      20  GCTGG      1  0.950208     0.91  0.965322
...      ...    ...    ...       ...      ...       ...
189332    20  TCTAC      1  0.997494     1.00  0.984278
189942    20  TCTAC      1  0.997645     0.93  0.572100
192150    20  GATCG      1  0.784588     0.74  0.089802
192471    20  GTTCT      1  0.999975     0.97  0.999997
195584    20  TCTAC      1  0.998743     0.93  0.995645

[293 rows x 6 columns]

In [18]:
demo_normal_20=Normal[Normal['indx']==20]
demo_normal_20

         indx   kmer  label  XGB_prob  RF_prob  SVM_prob
197825     20  ACTGG      0  0.000023     0.00  0.005133
197977     20  CTTCA      0  0.000807     0.07  0.043721
198818     20  CCTGC      0  0.000012     0.00  0.003775
198844     20  TGTTC      0  0.000097     0.00  0.003735
198951     20  GATCA      0  0.000009     0.00  0.000119
...       ...    ...    ...       ...      ...       ...
1820199    20  TGTGC      0  0.001502     0.05  0.021288
1820282    20  CCTGA      0  0.001553     0.00  0.001379
1820316    20  CATGA      0  0.001904     0.00  0.062781
1820848    20  GATCC      0  0.000026     0.00  0.000063
1821663    20  GGTGC      0  0.002180     0.01  0.013676

[2289 rows x 6 columns]

In [19]:
demo_False_20=demo_mod_20[demo_mod_20['XGB_prob']<=0.5]
demo_False_20

        indx   kmer  label  XGB_prob  RF_prob  SVM_prob
10505     20  GCTGG      1  0.352162     0.18  0.014373
21269     20  GATCG      1  0.034942     0.69  0.186787
39152     20  CATGA      1  0.026060     0.20  0.037343
41417     20  GGTGC      1  0.137078     0.63  0.021747
45473     20  CTTCA      1  0.385087     0.80  0.715329
51962     20  CGTGG      1  0.410887     0.62  0.003003
58171     20  CCTGA      1  0.420292     0.68  0.046438
69782     20  CCTGC      1  0.440465     0.72  0.050320
70193     20  GATCA      1  0.478457     0.80  0.189557
72499     20  GGTGG      1  0.369999     0.85  0.120984
75334     20  CGTGG      1  0.418677     0.81  0.151657
83942     20  CCTGC      1  0.410626     0.81  0.985818
86657     20  CCTGC      1  0.304472     0.28  0.114486
88002     20  CATCT      1  0.455192     0.67  0.031069
96263     20  AGTAC      1  0.125916     0.67  0.086637
96815     20  GATCA      1  0.324076     0.60  0.000008
99159     20  GCTGG      1  0.420615     0.73  0.091791
103425    20  GGTGC      1  0.266663     0.84  0.091328
104113    20  CCTGA      1  0.160767     0.62  0.101129
109034    20  CCTGC      1  0.122667     0.76  0.120157
118061    20  CCTGA      1  0.377747     0.74  0.948587
120535    20  CTTCT      1  0.089395     0.69  0.044585
137577    20  TCTTC      1  0.454757     0.71  0.023603
148165    20  GATCA      1  0.175573     0.02  0.003233
151156    20  CCTGG      1  0.271858     0.80  0.288705
155085    20  GGTGC      1  0.425104     0.24  0.039816
170924    20  CTTCA      1  0.326748     0.75  0.012635

In [25]:
AGTTC=Visual[Visual['kmer']=="AGTTC"]
AGTTC

         indx   kmer  label  XGB_prob  RF_prob  SVM_prob
80        260  AGTTC      1  0.999808     1.00  1.000000
1599      259  AGTTC      1  0.997499     0.90  0.999993
1829      243  AGTTC      1  0.983573     0.96  0.988261
2142      260  AGTTC      1  0.999894     0.98  1.000000
3070      260  AGTTC      1  0.999737     1.00  1.000000
...       ...    ...    ...       ...      ...       ...
1818323   260  AGTTC      0  0.000019     0.00  0.000301
1820621   161  AGTTC      0  0.011864     0.06  0.135134
1821325   240  AGTTC      0  0.000081     0.00  0.000390
1821871   260  AGTTC      0  0.000042     0.00  0.001392
1822332    33  AGTTC      0  0.000709     0.00  0.037365

[2633 rows x 6 columns]

In [26]:
AGTTC['indx'].value_counts()

260    1069
258     188
259     176
256      92
240      45
       ...
127       1
185       1
212       1
173       1
45        1
Name: indx, Length: 217, dtype: int64

In [28]:
mod_AGTTC=AGTTC[AGTTC['label']==1]
mod_AGTTC

        indx   kmer  label  XGB_prob  RF_prob  SVM_prob
80       260  AGTTC      1  0.999808     1.00  1.000000
1599     259  AGTTC      1  0.997499     0.90  0.999993
1829     243  AGTTC      1  0.983573     0.96  0.988261
2142     260  AGTTC      1  0.999894     0.98  1.000000
3070     260  AGTTC      1  0.999737     1.00  1.000000
...      ...    ...    ...       ...      ...       ...
194878   215  AGTTC      1  0.999713     0.99  0.993934
195266   216  AGTTC      1  0.999899     0.99  1.000000
195612   239  AGTTC      1  0.999376     0.97  0.999998
195838   260  AGTTC      1  0.999930     1.00  0.996089
196949   258  AGTTC      1  0.999851     0.96  1.000000

[315 rows x 6 columns]

In [30]:
mod_AGTTC['indx'].value_counts()

260    100
258     32
259     27
239     10
79      10
      ...
234      1
18       1
61       1
27       1
191      1
Name: indx, Length: 72, dtype: int64

In [31]:
mod_AGTTC.to_csv('/home/jiayi/5moU/data/DL_fromTombo/mod_AGTTC.csv')

In [33]:
Normal_AGTTC=AGTTC[AGTTC['label']==0]
Normal_AGTTC
Normal_AGTTC.to_csv('/home/jiayi/5moU/data/DL_fromTombo/normal_AGTTC.csv')

In [35]:
all_tombo=pd.read_csv('/home/jiayi/5moU/data/DL_fromTombo/all_tombo.csv')
all_tombo

,indx,kmer,mean_1,mean_2,mean_3,mean_4,mean_5,std_1,std_2,std_3,...,mdintense_2,mdintense_3,mdintense_4,mdintense_5,L-1,L-2,L-3,L-4,L-5,label
0,20,CATCT,-0.261382,-0.290529,-0.375176,-0.548695,-0.420694,0.034490,0.048193,0.075762,...,-0.302072,-0.405521,-0.548282,-0.413797,6,19,12,50,6,1
1,22,TCTTC,-0.375176,-0.548695,-0.420694,-0.102165,0.324141,0.075762,0.072908,0.065934,...,-0.548282,-0.413797,-0.103449,0.339314,12,50,6,29,12,1
2,23,CTTCG,-0.548695,-0.420694,-0.102165,0.324141,0.612248,0.072908,0.065934,0.077537,...,-0.413797,-0.103449,0.339314,0.643455,50,6,29,12,24,1
3,35,CGTGG,-0.134270,0.017096,0.317245,0.286391,0.191036,0.240493,0.116132,0.178935,...,0.000000,0.318624,0.264830,0.208968,29,38,6,19,6,1
4,44,CCTGC,-1.068734,-0.164691,0.164829,0.237456,-0.655237,0.200275,0.057011,0.052036,...,-0.165519,0.161381,0.240002,-0.657938,131,35,18,39,72,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1822819,350,GCTGG,0.160716,0.201952,0.291149,0.341133,0.261907,0.102909,0.062878,0.118291,...,0.194064,0.291096,0.343161,0.269796,22,6,980,14,6,0
1822820,365,GATCC,0.713934,0.005522,-0.667390,-0.689873,-0.575091,0.217518,0.459278,0.056848,...,0.030766,-0.688690,-0.655557,-0.570358,6,6,6,16,6,0
1822821,374,GATCC,0.404221,0.204545,-0.725696,-0.713145,0.062983,0.418295,0.532178,0.098837,...,0.508826,-0.731289,-0.707623,0.059166,10,7,2203,6,625,0
1822822,377,CCTGA,-0.713145,0.062983,0.264506,0.270585,0.073087,0.044437,0.174422,0.070813,...,0.059166,0.243763,0.250863,0.134898,6,625,34,6,17,0
1822823,380,GATCA,0.270585,0.073087,-0.577806,-0.538803,0.255019,0.056049,0.242040,0.213394,...,0.134898,-0.627157,-0.579825,0.257963,6,17,211,6,82,0

In [36]:
all_AGTTC=all_tombo[all_tombo['kmer']=="AGTTC"]
all_AGTTC

,indx,kmer,mean_1,mean_2,mean_3,mean_4,mean_5,std_1,std_2,std_3,...,mdintense_2,mdintense_3,mdintense_4,mdintense_5,L-1,L-2,L-3,L-4,L-5,label
80,260,AGTTC,0.513199,0.397293,-0.850444,-0.837177,-0.786233,0.047088,0.272815,0.031234,...,0.471305,-0.846254,-0.839970,-0.768751,6,81,6,15,104,1
1599,259,AGTTC,0.589209,0.568374,-0.717482,-0.762448,-0.789418,0.062266,0.080098,0.038712,...,0.579342,-0.727349,-0.763294,-0.799239,6,32,6,15,90,1
1829,243,AGTTC,0.458838,0.109656,-0.797939,-0.820008,-0.756034,0.149853,0.419986,0.034345,...,0.190347,-0.796560,-0.817250,-0.755180,13,6,6,33,63,1
2142,260,AGTTC,0.457595,0.472804,-0.688376,-0.681815,-0.679743,0.060894,0.174125,0.025067,...,0.513802,-0.686393,-0.686393,-0.696311,6,78,6,13,108,1
3070,260,AGTTC,0.528384,0.423719,-0.713185,-0.825872,-0.800544,0.029393,0.277885,0.162593,...,0.522379,-0.768558,-0.826600,-0.792575,6,51,6,11,108,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818323,260,AGTTC,0.787659,0.405793,-0.611869,-0.739305,-0.605124,0.169036,0.279195,0.138040,...,0.463995,-0.667700,-0.744655,-0.604325,32,14,6,11,17,0
1820621,161,AGTTC,0.396310,0.499622,-0.619268,-0.546544,-0.762006,0.090910,0.031997,0.130815,...,0.500937,-0.642935,-0.607435,-0.786905,39,6,6,16,16,0
1821325,240,AGTTC,0.589990,0.614284,-0.632994,-0.789089,-0.753708,0.172348,0.280588,0.188418,...,0.688070,-0.685807,-0.796713,-0.751445,6,40,6,19,6,0
1821871,260,AGTTC,0.661435,0.551367,-0.694797,-0.734620,-0.571503,0.110638,0.231089,0.049018,...,0.548295,-0.676666,-0.739763,-0.576580,33,34,6,11,6,0
1822332,33,AGTTC,0.695724,0.689144,-0.430299,-0.333123,-0.287625,0.108741,0.156471,0.050444,...,0.696973,-0.444039,-0.335371,-0.290405,6,56,6,20,31,0

In [37]:
all_AGTTC.to_csv('/home/jiayi/5moU/data/DL_fromTombo/all_AGTTC.csv',index=False)