In [1]:
import pandas as pd

In [2]:
motif_info=pd.read_csv('/home/jiayi/5moU/Code/DL5mou/DeepRead/motif_count.csv')
motif_info

      kmer  label  coverage
0    ACTAC      0     26917
1    ACTAC      1      3118
2    ACTGG      0     12301
3    ACTGG      1      1549
4    ACTTC      0     18476
..     ...    ...       ...
103  TGTAC      1      1022
104  TGTGC      0     12227
105  TGTGC      1      1612
106  TGTTC      0     39714
107  TGTTC      1      4622

[108 rows x 3 columns]